project_id = "xaoitjyuuxwksofmmydh"

[functions.detect-no-shows]
verify_jwt = false

[functions.process-renewals]
verify_jwt = false

[functions.process-waitlist]
verify_jwt = false

[functions.razorpay-webhook]
verify_jwt = false

[functions.create-payment]
verify_jwt = false
