services:
  - type: web
    name: libriofy-api-staging
    runtime: docker
    plan: standard
    branch: staging
    dockerfilePath: ./Dockerfile.api
    autoDeploy: false
    healthCheckPath: /health/ready
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: APP_ENV
        value: staging
      - fromGroup: libriofy-api-staging
  - type: web
    name: libriofy-api-production
    runtime: docker
    plan: standard
    branch: main
    dockerfilePath: ./Dockerfile.api
    autoDeploy: false
    healthCheckPath: /health/ready
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: APP_ENV
        value: production
      - fromGroup: libriofy-api-production
