// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { createSafeBrowserStorage } from '@/lib/browserStorage';
import { getStoredAccessToken } from '@/lib/authSession';
import { createInstrumentedBrowserSupabaseFetch } from '@/lib/observability/clientSupabaseFetch';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  throw new Error(
    "Missing Supabase environment variables. Expected VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY.",
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const sharedAuthOptions = {
  auth: {
    storage: createSafeBrowserStorage("local"),
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  global: {
    fetch: createInstrumentedBrowserSupabaseFetch(),
  },
};

export const supabaseAuth = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, sharedAuthOptions);

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  accessToken: getStoredAccessToken,
  global: {
    fetch: createInstrumentedBrowserSupabaseFetch(),
  },
});
